spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: security-service
#          uri: lb://SECURITY
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/security/**
          filters:
            - AuthenticationFilter

        - id: transaction-service
          uri: lb://ACCOUNTS
          predicates:
            - Path=/api/v1/accounts/**

        - id: account-service
          uri: lb://TRANSACTIONS
          predicates:
            - Path=/api/v1/transactions/**
server:
  port: 8765
