spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://SECURITY
          predicates:
            - Path=/api/v1/security/**
          filters:
            - AuthenticationFilter

        - id: account-service
          uri: lb://ACCOUNTS
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - AuthenticationFilter

        - id: transaction-service
          uri: lb://TRANSACTIONS
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - AuthenticationFilter
server:
  port: 8765
jwt:
  secret:${JWT_SECRET}
secret:
  key:${SECRET_KEY}
