spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://SECURITY
          predicates:
            - Path=/api/v1/security/**

        - id: transaction-service
          uri: lb://ACCOUNTS
          predicates:
            - Path=/api/v1/accounts/**

        - id: account-service
          uri: lb://TRANSACTIONS
          predicates:
            - Path=/api/v1/transactions/**
server:
  port: 8765
