version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      JWT_SECRET: 1B4BAF6A13B5301A3411C93C33630E8F7F219C5F8F3344E7CF
      SECRET_KEY: aa03a1026308ee37bea413f05e293f29a8c053c3aff74b69c1ad3fdbcd544dc4

  accounts-service:
    build:
      context: ./accounts
    ports:
      - "8089:8089"
    depends_on:
      - accountsdb
      - eureka-server
      - kafka
    environment:
      DB_URL: jdbc:postgresql://accountsdb:5432/accounts_db
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      SECRET_KEY: aa03a1026308ee37bea413f05e293f29a8c053c3aff74b69c1ad3fdbcd544dc4
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  notifications-service:
    build:
      context: ./notifications
    ports:
      - "8091:8091"
    depends_on:
      - eureka-server
      - kafka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SECRET_KEY: aa03a1026308ee37bea413f05e293f29a8c053c3aff74b69c1ad3fdbcd544dc4
      TWILIO_SSID: ACa31ec31aeaf0c9f8af0685592655b8a2
      TWILIO_TOKEN: 684d9b486dd2446a2ac473bfc827b2d0
      TWILIO_PHONE: +19708250562
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  transactions-service:
    build:
      context: ./transactions
    ports:
      - "8090:8090"
    depends_on:
      - transactionsdb
      - eureka-server
    environment:
      DB_URL: jdbc:postgresql://transactionsdb:5432/transactions_db
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      SECRET_KEY: aa03a1026308ee37bea413f05e293f29a8c053c3aff74b69c1ad3fdbcd544dc4
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

  security-service:
    build:
      context: ./security
    ports:
      - "8092:8092"
    depends_on:
      - usersdb
      - eureka-server
      - otpdb
      - kafka
    environment:
      DB_URL: jdbc:postgresql://usersdb:5432/users_db
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      REDIS_HOST: otpdb
      REDIS_PORT: 6379
      SECRET_KEY: aa03a1026308ee37bea413f05e293f29a8c053c3aff74b69c1ad3fdbcd544dc4
      JWT_SECRET: 1B4BAF6A13B5301A3411C93C33630E8F7F219C5F8F3344E7CF
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  accountsdb:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: accounts_db
    volumes:
      - accounts_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  transactionsdb:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: transactions_db
    volumes:
      - transactions_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  usersdb:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users_db
    volumes:
      - users_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  otpdb:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - otp_data:/var/lib/redis/data

volumes:
  otp_data:
  accounts_data:
  transactions_data:
  users_data:
